import { AppleMusicIcon } from "./AppleMusicIcon"
import { FacebookIcon } from "./FacebookIcon"
import { InstagramIcon } from "./InstagramIcon"
import { SpotifyIcon } from "./SpotifyIcon"
import { YoutubeIcon } from "./YoutubeIcon"
import { EngIcon } from "./EngIcon"
import { CatIcon } from "./CatIcon"
import { DonateIcon } from "./DonateIcon"
import { DownloadIcon } from "./DownloadIcon"
import { SheetIcon } from "./SheetIcon"
import { PoemIcon } from "./PoemIcon"
import { PlayIcon } from "./PlayIcon"
import { PauseIcon } from "./PauseIcon"

export { SpotifyIcon, AppleMusicIcon, InstagramIcon, YoutubeIcon, FacebookIcon, EngIcon, CatIcon, DonateIcon, DownloadIcon, SheetIcon, PoemIcon, PlayIcon, PauseIcon}