export type Song =       {
  number: number,
  title: string,
  engTitle?: string,
  link: string,
  download: string,
  sheet?: string,
  poem?: string
}

export type Album = {
  title: string,
  engTitle: string,
  catDescription: string,
  engDescription: string,
  img: string,
  year: number,
  spotifyLink: string,
  youtubeLink: string,
  songs: Song[]
}

export const albums: Album[] = [
  {
    title: "Captura subtil",
    engTitle: "Subtle Capture",
    catDescription: "Aquest primer treball, on cada cançó va acompanyada d'un poema, és un homenatge a aquelles emocions i intuïcions que se'ns mouen per dins, profundes i sense fer soroll... fins que afloren de cop i ho prenen tot.",
    engDescription: "",
    img: "/captura_subtil.jpg",
    year: 2016,
    spotifyLink: "https://open.spotify.com/intl-es/album/3kw6YVcxOHF78yoStWeFGV?si=CUCczvHQTyi-toGwUFgFiw",
    youtubeLink: "https://www.youtube.com/watch?v=4l1vCxnO8D4",
    songs: [
      {
        number: 1,
        title: "Aquell petit arbre",
        engTitle: "",
        link: "https://docs.google.com/uc?export=play&id=1Qou-tYSqi56I3UQe98Tpor_POLdUWVVE", 
        download: "https://docs.google.com/uc?export=download&id=1Qou-tYSqi56I3UQe98Tpor_POLdUWVVE",
        sheet: "",
        poem: "aquell-petit-arbre",
      },
      {
        number: 2,
        title: "Cada gota",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "cada-gota",
      },
      {
        number: 3,
        title: "Castell de sorra",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "castell-de-sorra",
      },
      {
        number: 4,
        title: "Fidipides",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "fidipides",
      },
      {
        number: 5,
        title: "Seguirem buscant",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "seguirem-buscant",
      },
      {
        number: 6,
        title: "El bosc dels records",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "el-bosc-dels-records",
      },
      {
        number: 7,
        title: "Pres per dins",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "pres-per-dins",
      },
      {
        number: 8,
        title: "Xiprers",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "xiprers",
      },
      {
        number: 9,
        title: "Ballarismes",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "ballarismes",
      },
      {
        number: 10,
        title: "D'entre els cels",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
        poem: "d-entre-els-cels",
      },
      {
        number: 11,
        title: "Allegro",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      }
    ]
  },
  {
    title: "Becaines d'estiu",
    engTitle: "Summer Siesta",
    catDescription: "Single compost durant dos dies mandrosos d'estiu, d'aquells xafogosos, on el bon temps se't tira a sobre... la cançó vol captar aquest esperit estiuenc.",
    engDescription: "",
    img: "/becaines_destiu.jpg",
    year: 2017,
    spotifyLink: "https://open.spotify.com/intl-es/album/3NZSl6a63jfHvzVfrFjsoj?si=xsNTB3nmR9i33vm6IP7RVg",
    youtubeLink: "https://www.youtube.com/watch?v=ShiWROJ5ARA",
    songs: [
      {
        number: 1,
        title: "Becaines d'estiu",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
    ]
  },
  {
    title: "Versions I",
    engTitle: "Versions I",
    catDescription: "Recull de versions de cançons ja existents, adaptades a guitarra sola. Totes les peces, d'origens diversos, es caracteritzen pel seu so calmat i familiar.",
    engDescription: "",
    img: "/versions.jpg",
    year: 2018,
    spotifyLink: "https://open.spotify.com/intl-es/album/3VsXXCGpDk4DmhfqFq0U7k?si=7aQXHg5sTL-dLGCXJRz02g",
    youtubeLink: "https://www.youtube.com/watch?v=NfcBHuHtOe0",
    songs: [
      {
        number: 1,
        title: "Reflections in D",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 2,
        title: "Cançó de suburbi",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 3,
        title: "Bad Day",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 4,
        title: "The Girl from Ipanema",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 5,
        title: "Waltz of Chihiro",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 6,
        title: "Fletcher's Song in a Club",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 7,
        title: "You Raise Me Up",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 8,
        title: "What a Wonderful World",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      }
    ]
  },
  {
    title: "El fred i la primavera",
    engTitle: "Breeze & Spring",
    catDescription: "Aquest últim àlbum, més madur i de caire conceptual, busca plasmar musicalment l'ampli ventall d'emocions que som capaços de sentir, i la intensitat amb què poden aparèixer, esvanir-se, conviure, confondre's... Tristesa, desig, dubte, il·lusió, dolor, enyor, transformació... som barreges de tot això i mil forces més, en xoc continu.",
    engDescription: "",
    img: "/el_fred_i_la_primavera.jpg",
    year: 2022,
    spotifyLink: "https://open.spotify.com/intl-es/album/7rV5S7qfyVeDpGZsfrzo1c?si=o6snXPNAQoivGFoguYGYKw",
    youtubeLink: "https://www.youtube.com/watch?v=AdoTT5BJvzs",
    songs: [
      {
        number: 1,
        title: "Flor de cirerer",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 2,
        title: "Les fulles verdes",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 3,
        title: "Els ocells",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 4,
        title: "Llavor",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 5,
        title: "Els ocells tornen",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      }
    ]
  }
]