export const musicLinks = [
  {
    title: "Captura subtil",
    catDescription: "Primer disc, publicat el 2016. Cada cançó va acompanyada d'un poema.",
    engDescription: "",
    img: "./img/captura_subtil.jpg",
    spotifyLink: "https://open.spotify.com/intl-es/album/3kw6YVcxOHF78yoStWeFGV?si=CUCczvHQTyi-toGwUFgFiw",
    youtubeLink: "https://www.youtube.com/watch?v=4l1vCxnO8D4",
    songs: [
      {
        number: 1,
        title: "Aquell petit arbre",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 2,
        title: "Cada gota",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 3,
        title: "Castell de sorra",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 4,
        title: "Fidipides",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 5,
        title: "Seguirem buscant",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 6,
        title: "El bosc dels records",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 7,
        title: "Pres per dins",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 8,
        title: "Xiprers",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 9,
        title: "Ballarismes",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 10,
        title: "D'entre els cels",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      },
      {
        number: 11,
        title: "Allegro",
        engTitle: "",
        link: "",
        download: "",
        sheet: "",
      }
    ]
  },
]